stages:          # List of stages for jobs, and their order of execution
  - deploy

deploy-job:      # This job runs in the deploy stage.
  stage: deploy  # It only runs when *both* jobs in the test stage complete successfully.
  
  only:
    refs:
      - main
  
  image: nikolaik/python-nodejs:python3.8-nodejs19

  variables:
    REGION: us-east-2

  before_script:
    - cd react-vite
    - yarn

  environment: production

  script:
    - pip3 install awscli
    - CI=false yarn build
    - aws --region $REGION s3 cp --recursive ./dist/ s3://react-blockchain-app/
    - cd ..
